runtime: python39

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: .*
  static_files: index.html
  upload: index\.html

- url: /.*
  script: auto

skip_files:
- .git*
- app.yaml
- README.md
